---
title: 'Arrange'
author: 'w203: Statistics for Data Science'
date: "8/13/2020"
output: github_document
---

```{r setup, results='hide', warning=FALSE, message=FALSE}
library(tidyverse)
```

```{r load data}
agencies <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/agencies.csv')
launches <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-15/launches.csv')
```

# Task 

Using the `launches` data, the `arrange()` verb, and the `head()` verb: 

- Print the earliest launches

```{r}
launches %>% 
  arrange(launch_date) %>% 
  head()
```

- Still using the head verb, use the `desec()` adverb to print the *most recent* launches

```{r}
launches %>% 
  arrange(desc(launch_date)) %>% 
  head()
```

Adding in the `state_code` variable, 

- Arrange the data so that it is sorted first by `launch_year` and then by `state_code`

```{r}
launches %>% 
  arrange(launch_year, state_code)
```




